### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by gattopane** [FileEye/pel#4]
Hello! I've been considering using this library, as it is the only PHP-native one that lets you modify EXIF data, but I'm a little hesitant due to the GPL license. I know there was a [discussion in the parent project](https://github.com/pel/pel/pull/47) about changing it to LGPL or MIT, but I'd like to know: is that change being considered for this fork?

Thanks!

**Comment by mondrake** [comment]
I would have no problem to change licensing to LGPL 3, but I guess all former contributors should agree and have no clue how to reach that consensus. Also, I will not actively look towards that - my need with this fork being almost exclusively to ensure compatibility with latest PHP versions, which was difficult to get in the parent project.

If I get a PR with a compelling legal framework to execute the change, I will merge it.

Thanks!

**Comment by gattopane** [comment]
Understood, thank you!
